theme: jekyll-theme-minimal
title: Victor Siqueira
description: Welcome to my resumé
<br/>
My research interests include Social Media Studies,<br/>
Natural Language Processing, Comparative Politics,<br/>
Electoral Governance and AI.
